### PR TITLE
Upgrade cli

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by keithamus** [comment]
Thanks @SimenB. Build passing so I'll merge this 😄

**Comment by SimenB** [comment]
@keithamus could you do a release as well? 😄

**Comment by keithamus** [comment]
Will be a breaking change because of #17

**Comment by keithamus** [comment]
[`4.0.0`](https://www.npmjs.com/package/hashmark)

**Comment by SimenB** [comment]
Great, thanks!

Just a quick note that it was actually the changes in #20 which were breaking for us 😄 

That PR was made by the guy who used to sit next to me at work as well, which I find funny

**Comment by keithamus** [comment]
😲 well I'm glad I released it at `4.0.0` then!

**Pull request merged**
