### PR TITLE
A couple readme corrections and renaming functionality

### PR DESCRIPTION
**Pull request by michaeljwilliams**
Add functionality to rename input files with a hash as opposed to outputting hashed copies of input files. Add -r/--rename option to cli.

I wanted this functionality, so I added it. Let me know what you think.

### CODE REVIEW

**Comment by keithamus** [comment]
Looks awesome! Thanks @michaeljwilliams :smile: 

Could you please add some tests? Then I'll merge :+1:

**Comment by michaeljwilliams** [comment]
Tests in the package.json like yours? Sorry, I'm pretty new to this. I did
test it though haha!

**Comment by keithamus** [comment]
Thats fine @michaeljwilliams, the tests are a little bit funny on this project.

Just make a new "npm script" - add a "test13" to the package.json like so:

```js
"scripts": {
  "...":"...",
  "test13": "echo Test1 > test.js && ./bin/hashmark -l 4 -n test.js -r '{name}-{hash}{ext}' && test ! -f test.js && rm test-7e5e.js",
  "test": "for i in {1..13}; do npm run test$i; done"
},
```

Don't forget to change the "test" script from `1..12` to `1..13`. Add as many tests as you feel covers the functionality.

**Comment by michaeljwilliams** [comment]
I have done so. I only think one test is really required because I didn't change much. By the way, what does the `test ! -f` part mean?

**Comment by michaeljwilliams** [comment]
@keithamus bump?

**Comment by keithamus** [comment]
Hey sorry @michaeljwilliams! Merged :smile:

**Comment by michaeljwilliams** [comment]
Thanks!

**Pull request merged**
